title: Tom Sarry
logo: /assets/img/logo.png
description: ğŸŒ± Junior Software Developer
  <br>
  <br>
  <a href="https://github.com/tomsarry" target="_blank">ğŸ’» Github</a>
  <br>
  <a href="https://www.linkedin.com/in/tomsarry" target="_blank">ğŸ“ LinkedIn</a>
  <br>
  <a href="https://blog.tomsarry.com" target="_blank">ğŸ“š Blog</a>
  <hr/>
  <a href="https://letterboxd.com/tomsarry/" target="_blank">ğŸ¬ Letterboxd</a>
  <br>
  <a href="https://www.goodreads.com/user/show/156270147" target="_blank">ğŸ“– Goodreads</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
# plugins:
#   - jekyll-redirect-from
